const products =[
	{
		id: '1',
		name:'Airpod',
		image: '/Images/airpods.jpg',
		description:'AirPods are wireless earbuds developed by Apple. They provide high-quality audio, seamless connectivity with Apple devices, and a compact, stylish design. With features like Siri integration and quick charging, AirPods offer a premium audio experience.',
		brand:'Apple',
		category:'Electronics',
		price: 250.00,
		countInStock:4,
		rating:3.5,
		numReviews:4,
	},
	{
		id: '2',
		name: 'Galaxy Watch',
		image: '/Images/airpods.jpg',
		description:'AirPods are wireless earbuds developed by Apple. They provide high-quality audio, seamless connectivity with Apple devices, and a compact, stylish design. With features like Siri integration and quick charging, AirPods offer a premium audio experience.',
		brand: 'Samsung',
		category: 'Wearables',
		price: 199.99,
		countInStock: 8,
		rating: 4.2,
		numReviews: 6,
	},
    
	{
		id: '3',
		name: 'Smart Home Camera',
		image: '/Images/airpods.jpg',
		description:'AirPods are wireless earbuds developed by Apple. They provide high-quality audio, seamless connectivity with Apple devices, and a compact, stylish design. With features like Siri integration and quick charging, AirPods offer a premium audio experience.',
		brand: 'Nest',
		category: 'Home Security',
		price: 129.95,
		countInStock: 12,
		rating: 4.8,
		numReviews: 10,
	},
    
	{
		id: '4',
		name: 'Wireless Keyboard',
		image: '/Images/airpods.jpg',
		description:'AirPods are wireless earbuds developed by Apple. They provide high-quality audio, seamless connectivity with Apple devices, and a compact, stylish design. With features like Siri integration and quick charging, AirPods offer a premium audio experience.',
		brand: 'Logitech',
		category: 'Computer Accessories',
		price: 49.99,
		countInStock: 20,
		rating: 4.0,
		numReviews: 8,
	},
    
	{
		id: '5',
		name: 'Bluetooth Speaker',
		image: '/Images/airpods.jpg',
		description:'AirPods are wireless earbuds developed by Apple. They provide high-quality audio, seamless connectivity with Apple devices, and a compact, stylish design. With features like Siri integration and quick charging, AirPods offer a premium audio experience.',
		brand: 'JBL',
		category: 'Audio',
		price: 79.99,
		countInStock: 15,
		rating: 4.5,
		numReviews: 7,
	},
    
	{
		id: '6',
		name: '4K Smart TV',
		image: '/Images/airpods.jpg',
		description:'AirPods are wireless earbuds developed by Apple. They provide high-quality audio, seamless connectivity with Apple devices, and a compact, stylish design. With features like Siri integration and quick charging, AirPods offer a premium audio experience.',
		brand: 'Sony',
		category: 'Televisions',
		price: 799.00,
		countInStock: 0,
		rating: 4.6,
		numReviews: 12,
	},
    
];
export default products;
